title: Matt McManus
author: Matt McManus
url: https://mcmanus.io
description: In which I attempt to share my thoughts on how to be human
permalink: /:year/:title
# paginate: 100
# paginate_path: "blog/page:num"

include:
  - _redirects
exclude:
  - src
  - node_modules

repository: mattmcmanus/mattmcmanus.github.io

collections:
  category_details:
    output: true
    permalink: /category/:name

defaults:
  - scope:
      type: "category_details"
    values:
      layout: "category"

logo: /siteicon.png
sass:
  sass_dir: _scss
  style: :compressed

autoprefixer:
  only_production: true
  browsers:
    - last 2 versions

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

twitter:
  username: mattmcmanus

social:
  name: Matt McManus
  links:
    - https://twitter.com/mattmcmanus
    - https://www.linkedin.com/in/mattmcmanus
    - https://github.com/mattmcmanus
    - https://keybase.io/mattmcmanus

plugins:
  # - jekyll-autoprefixer
  # - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-default-layout

feed:
  path: atom.xml
