title: Matt McManus
author: Matt McManus
url: https://mcmanus.io
description: In which I attempt to share my thoughts on how to be human
permalink: /:year/:title

include:
  - _redirects
exclude:
  - src
  - node_modules
  - .sass-cache
  - Paw.paw
  - tailwind.js
  - yarn.lock
  - functions-src

repository: mattmcmanus/mattmcmanus.github.io

collections:
  notes:
    output: true
    permalink: /notes/:year/:month/:day/:title
  category_details:
    output: true
    permalink: /category/:name

defaults:
  - scope:
      type: "category_details"
    values:
      layout: "category"
  - scope:
      path: ''
      type: 'notes'
    values:
      categories: note
      layout: "note"

logo: /siteicon.png
sass:
  sass_dir: _scss
  style: :compressed

autoprefixer:
  only_production: true
  browsers:
    - last 2 versions

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

twitter:
  username: mattmcmanus

social:
  name: Matt McManus
  links:
    - https://twitter.com/mattmcmanus
    - https://www.linkedin.com/in/mattmcmanus
    - https://github.com/mattmcmanus
    - https://keybase.io/mattmcmanus

plugins:
  # - jekyll-autoprefixer
  # - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-webp
  - jekyll-paginate-v2
  # - jekyll-default-layout

feed:
  path: atom.xml

env: production
# minify_html: false

webp:
  enabled: true
  quality: 60
  img_dir: ["/images"]
  formats: [".jpeg", ".jpg", ".png"]
  regenerate: false
  exclude: []

pagination:
  enabled: true
  per_page: 10
  permalink: '/blog/:num/' # Pages are index.html inside this folder (default)
  trail:
    before: 2
    after: 2
